# Generated by Django 6.0.5 on 2026-05-19 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blizzard", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="playablerace",
            table="playable_races",
        ),
        migrations.CreateModel(
            name="PlayableRaceClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_id", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("image_url", models.URLField(max_length=512)),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playable_classes",
                        to="blizzard.playablerace",
                    ),
                ),
            ],
            options={
                "db_table": "playable_race_classes",
                "ordering": ["name"],
                "unique_together": {("race", "class_id")},
            },
        ),
    ]
