# Generated by Django 6.0.5 on 2026-05-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blizzard", "0002_alter_playablerace_table_playableraceclass"),
    ]

    operations = [
        migrations.AddField(
            model_name="playableraceclass",
            name="synced_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
