# Generated by Django 6.0.5 on 2026-05-28 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blizzard", "0003_playableraceclass_synced_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayableClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_id", models.PositiveIntegerField(db_index=True, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("image_url", models.URLField(max_length=512)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "playable_classes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PlayableClassSpecialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spec_id", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("image_url", models.URLField(max_length=512)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "playable_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specializations",
                        to="blizzard.playableclass",
                    ),
                ),
            ],
            options={
                "db_table": "playable_class_specializations",
                "unique_together": {("playable_class", "spec_id")},
            },
        ),
    ]
