# Generated by Django 6.0.5 on 2026-06-11 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blizzard", "0004_playableclass_playableclassspecialization"),
    ]

    operations = [
        migrations.AddField(
            model_name="playableclassspecialization",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="playableclassspecialization",
            name="role_name",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.CreateModel(
            name="PlayableClassSpecializationSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_id", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("image_url", models.URLField(blank=True, default="", max_length=512)),
                ("description", models.TextField(blank=True, default="")),
                ("cast_time", models.CharField(blank=True, default="", max_length=128)),
                (
                    "power_cost",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("range", models.CharField(blank=True, default="", max_length=128)),
                ("cooldown", models.CharField(blank=True, default="", max_length=128)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "specialization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="blizzard.playableclassspecialization",
                    ),
                ),
            ],
            options={
                "db_table": "playable_class_specialization_skills",
                "ordering": ["skill_id"],
                "unique_together": {("specialization", "skill_id")},
            },
        ),
    ]
